services:
  - type: web
    name: damxd89-ultimate-bot
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 3000
      - key: BOT_TOKEN
        sync: false
      - key: NOTIFY_BOT_TOKEN
        sync: false
      - key: ENDER_KEY
        sync: false
      - key: CASHFREE_CLIENT_ID
        sync: false
      - key: CASHFREE_CLIENT_SECRET
        sync: false
      - key: CASHFREE_ENV
        value: PRODUCTION
      - key: NOWPAYMENTS_API_KEY
        sync: false
      - key: ADMIN_USER_ID
        sync: false
